config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root to: 'homes#top'
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
resources :genres
  authenticated :admin do
    get 'admin_page', to: 'admin/posts#date_base'
    resources :posts, only: [] do
      delete '', to: 'posts#destroy', as: :destroy
      resources :post_comments, only: [:destroy]
    end
  end

  namespace :admin do
    resources :posts, only: [:index] do
      member do
        delete 'destroy_comment', to: 'posts#destroy_comment', as: 'destroy_comment'
        delete 'destroy_post', to: 'posts#destroy_post', as: 'destroy_post'
      end
    end
  end

  resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :likes, only: [:index]
    resources :post_comments, only: [:create]

    collection do
      get 'search'
    end
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
   before_action :check_guest, only: :create
   

   
def index
  likes = Like.where(user_id: current_user.id).pluck(:post_id)
 like_posts = Post.where(id: likes)
  @posts = Kaminari.paginate_array(like_posts).page(params[:page]).per(3)

end

 def create
  @post = Post.find(params[:post_id])
  like = current_user.likes.new(post_id: @post.id, user_id: current_user.id)
  like.save
 end

def destroy
  @post = Post.find(params[:post_id])
  like = current_user.likes.find_by(post_id: @post.id, user_id: current_user.id)
  like.destroy
end

private
  def set_user
    @user = current_user
  end
  def check_guest
    if current_user.guest?
      redirect_to root_path, alert: "ゲストユーザーはいいね機能を使用できません。"
    end
  end
end

app/views/likes/_index.html.erb
<% if current_user %>
  <% @posts.each do |post| %>
    <% if current_user.likes.exists?(post_id: post.id) %>
      <div class="post-item">
        <%= link_to post.title, post_path(post.id) %>
        <p>投稿者 <%= post.user.name if post.user.present? %></p>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/likes/_like.html.erb
<% unless post.liked?(current_user) %>
  <%= link_to post_likes_path(post),  remote: true, method: :post do %>
    <!--<i class="fas fa-heart"></i>-->
    <%= post.likes.count %>
  <% end %>
<% else %>
  <%= link_to post_likes_path(post), method: :delete, remote: true do %>
    <!--<i class="far fa-heart"></i>-->
    <span><%= post.likes.count %></span>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$('#favorite_btn_<%= @post.id %>').html('<%= j(render  'likes/like',  post: @post ) %>');

app/views/likes/destroy.js.erb
$('#favorite_btn_<%= @post.id %>').html('<%= j(render  'likes/like',  post: @post ) %>');