config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root to: 'homes#top'
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
resources :genres
  authenticated :admin do
    get 'admin_page', to: 'admin/posts#date_base'
    resources :posts, only: [] do
      delete '', to: 'posts#destroy', as: :destroy
      resources :post_comments, only: [:destroy]
    end
  end

  namespace :admin do
    resources :posts, only: [:index] do
      member do
        delete 'destroy_comment', to: 'posts#destroy_comment', as: 'destroy_comment'
        delete 'destroy_post', to: 'posts#destroy_post', as: 'destroy_post'
      end
    end
  end

  resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :likes, only: [:index]
    resources :post_comments, only: [:create]

    collection do
      get 'search'
    end
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :post_comments, dependent: :destroy
  belongs_to :user
  has_many :likes
  has_many :liking_users, through: :likes, source: :user
  has_one_attached :image
  belongs_to :genre

  validates :title, presence: true
  validates :body, presence: true

  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @post = Post.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @post = Post.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @post = Post.where("title LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end


  def liked?(user)
    user.present? && likes.where(user_id: user.id).exists?
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  
  def date_base
    @comments = PostComment.all
    @posts = Post.all
    @users = User.all
  end

  def destroy_comment
    comment = PostComment.find(params[:id])
    comment.destroy
    redirect_to admin_page_path, notice: 'コメントが削除されました。'
  end


def destroy_post
  @post = Post.find(params[:id])
  @post.destroy
  redirect_to admin_page_path, notice: '投稿が削除されました。'
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :destroy]
  before_action :authenticate_admin!, only: [:destroy]

def index
  if params[:genre].present?
    @posts = Post.includes(:genre).where(genres: { id: params[:genre] })
  else
    @posts = Post.all
  end
  @genres = Genre.all
end


  def new
    @post = Post.new
    @genres = Genre.all
  end

def create
  @post = Post.new(post_params)
  @post.user_id = current_user.id
  @genres = Genre.all
  @post.genre_id = params[:post][:genre_id] # ジャンルの選択値を設定する

  if @post.save
    redirect_to @post, notice: "投稿が作成されました。"
  else
    render :new
  end
end




  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @posts = [@post]
    @genres = Genre.all
  end
  
def destroy
  @post = Post.find(params[:id])
  @post.destroy
  redirect_to posts_path, notice: '投稿が削除されました。'
end

  private

  def post_params
    params.require(:post).permit(:title, :body, :genre_id, :image)
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_comment.html.erb
    <div class="col-md-6">
        <ul class="list-group">
      <% @comments.each do |comment| %>
          <li class="list-group-item"><%= comment.comment %>
         
         <% if admin_signed_in? %>
  <%= link_to '削除',  destroy_comment_admin_post_path(comment), method: :delete, data: { confirm: '本当に削除しますか？' } %>
<% end %>
</li>
      <% end %>
</ul>
    </div>

app/views/admin/posts/_posts.html.erb
<div class="col-md-6">
      <% @posts.each do |post| %>
        <div class="card mb-3">
          <div class="card-body">
            <p class="card-title"><%= post.title %></p>
            <% if admin_signed_in? %>
  <%= link_to '削除', destroy_post_admin_post_path(post), method: :delete, data: { confirm: '本当に削除しますか？' } %>
<% end %>
          </div>
        </div>
      <% end %>
    </div>

app/views/admin/posts/_user.html.erb
    <div class="col-md-6">
      <ul class="list-group">
        <% @users.each do |user| %>
          <li class="list-group-item"><%= user.name %></li>
        <% end %>
      </ul>
    </div>

app/views/admin/posts/date_base.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1>コメント一覧</h1>
<%= render partial: 'comment' %>
    <div class="col-md-6">
      <h1>投稿記事一覧</h1>
<%= render partial: 'posts' %>
  <div class="row">
    <div class="col-md-6">
      <h1>ユーザー一覧</h1>
 <%= render partial: 'user'%>
  </div>
</div>