config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root to: 'homes#top'
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
resources :genres
  authenticated :admin do
    get 'admin_page', to: 'admin/posts#date_base'
    resources :posts, only: [] do
      delete '', to: 'posts#destroy', as: :destroy
      resources :post_comments, only: [:destroy]
    end
  end

  namespace :admin do
    resources :posts, only: [:index] do
      member do
        delete 'destroy_comment', to: 'posts#destroy_comment', as: 'destroy_comment'
        delete 'destroy_post', to: 'posts#destroy_post', as: 'destroy_post'
      end
    end
  end

  resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :likes, only: [:index]
    resources :post_comments, only: [:create]

    collection do
      get 'search'
    end
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :post_comments, dependent: :destroy
  belongs_to :user
  has_many :likes
  has_many :liking_users, through: :likes, source: :user
  has_one_attached :image
  belongs_to :genre

  validates :title, presence: true
  validates :body, presence: true

  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @post = Post.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @post = Post.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @post = Post.where("title LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end


  def liked?(user)
    user.present? && likes.where(user_id: user.id).exists?
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  
  def date_base
    @comments = PostComment.all
    @posts = Post.all
    @users = User.all
  end

  def destroy_comment
    comment = PostComment.find(params[:id])
    comment.destroy
    redirect_to admin_page_path, notice: 'コメントが削除されました。'
  end


def destroy_post
  @post = Post.find(params[:id])
  @post.destroy
  redirect_to admin_page_path, notice: '投稿が削除されました。'
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :destroy]
  before_action :authenticate_admin!, only: [:destroy]

def index
  if params[:genre].present?
    @posts = Post.includes(:genre).where(genres: { id: params[:genre] })
  else
    @posts = Post.all
  end
  @genres = Genre.all
end


  def new
    @post = Post.new
    @genres = Genre.all
  end

def create
  @post = Post.new(post_params)
  @post.user_id = current_user.id
  @genres = Genre.all
  @post.genre_id = params[:post][:genre_id] # ジャンルの選択値を設定する

  if @post.save
    redirect_to @post, notice: "投稿が作成されました。"
  else
    render :new
  end
end




  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @posts = [@post]
    @genres = Genre.all
  end
  
def destroy
  @post = Post.find(params[:id])
  @post.destroy
  redirect_to posts_path, notice: '投稿が削除されました。'
end

  private

  def post_params
    params.require(:post).permit(:title, :body, :genre_id, :image)
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/posts/_sidebar.html.erb
<div class="sidebar">
  <div class="profile">
    <% if user_signed_in? %>
      <%= link_to edit_user_registration_path do %>
        <%= current_user.name %>
      <% end %>
    <% else %>

    <% end %>
  </div>

  <div class="new-post">
    <% if user_signed_in? %>
      <%= link_to "New Post", new_post_path, class: "btn btn-primary btn-block mb-3" %>
    <% end %>
  </div>
  
   <div class="new-post">
     <%= render "likes/index", collection: @like_posts %>
   </div>
  
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'sidebar' %>
    </div>
    <div class="col-md-9">
      <div class="row">
        <% @posts.each do |post| %>
        <div class="col-lg-3 mb-3">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><%= link_to post.title, post_path(post) %></h5>
              <p class="card-text"><%= truncate(post.body, length: 100) %></p>
              <div class="row">
                <div class="col-md-6">
                  <small class="text-muted"><%= post.created_at.strftime("%Y/%m/%d") %></small>
                </div>
                <p>評価値: <%= @rating %></p>
                <div class="col-md-6">
                  <div class="d-flex justify-content-end">
                    <%= link_to "詳細を見る", post_path(post), class: "btn btn-primary btn-sm" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">新規投稿</div>
        <div class="card-body">
          <%= form_with(model: @post, url: posts_path, class: "form-horizontal", enctype: "multipart/form-data") do |form| %>
            <% if @post.errors.any? %>
              <div id="error_explanation" class="alert alert-danger">
                <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

                <ul>
                <% @post.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group">
              <%= form.label :title, class: "col-sm-3 control-label" %>
              <div class="col-sm-9">
                <%= form.text_field :title, class: "form-control" %>
              </div>
            </div>

<div class="form-group">
  <%= form.label :genre_id, class: "col-sm-3 control-label" %>
  <div class="col-sm-9">
    <%= form.collection_select :genre_id, Genre.all, :id, :name, prompt: "ジャンルを選択してください", class: "form-control" %>
  </div>
</div>

            <div class="form-group">
              <%= form.label :body, class: "col-sm-3 control-label" %>
              <div class="col-sm-9">
                <%= form.text_area :body, class: "form-control" %>
              </div>
            </div>

            <div class="form-group">
              <%= form.label :image, class: "col-sm-3 control-label" %>
              <div class="col-sm-9">
                <%= form.file_field :image, class: "form-control-file" %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-offset-3 col-sm-9">
                <%= form.submit "投稿する", class: "btn btn-primary" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row my-4"></div>
  <div class="row">
    <div class="col-md-2">
      <%= render 'sidebar' %>
    </div>
    <div class="col-md-9">
      <div class="card mb-3" style="max-width: 1200px;">
        <div class="row g-0">
          <div class="col-md-4">
            <% if @post.image.attached? %>
              <%= image_tag @post.image, class: "card-img-top h-100 w-100" %>
            <% else %>
              <%= image_tag "142_refileDownloadImage", class: "card-img-top h-100 w-100" %>
            <% end %>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title" style="font-size: 32px;"><%= @post.title %></h5>
              <p class="card-text" style="font-size: 24px;"><%= @post.body %></p>
              <ul class="list-group list-group-flush">
                 <div id="favorite_btn_<%= @post.id %>">
                 <%= render 'likes/like',  post: @post  %>
                 </div>
                <li class="list-group-item" style="font-size: 24px;">ジャンル: <%= @post.genre.name %></li>
                <li class="list-group-item" style="font-size: 24px;">投稿日: <%= @post.created_at.strftime("%Y/%m/%d") %></li>
                <li class="list-group-item" style="font-size: 24px;">評価:</li>
<% if admin_signed_in? %>
  <%= link_to '削除', post_path(@post), method: :delete, data: { confirm: '本当に削除しますか？' } %>
<% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="card mb-3" style="max-width: 1200px;">
        <div class="card-body">
          <h5 class="card-title">コメント</h5>
          <div class="comments">
            <p class="comment-count">コメント件数: <%= @post.post_comments.count %></p>
            <% @post.post_comments.each do |post_comment| %>
              <div class="comment">
                <p class="comment-date"><%= post_comment.created_at.strftime('%Y/%m/%d') %> <%= post_comment.user.name %></p>
                <p class="comment-content"><%= post_comment.comment %></p>
<% if admin_signed_in? %>
  <%= link_to '削除', post_post_comment_path(@post, post_comment), method: :delete, data: { confirm: '本当に削除しますか？' } %>
<% end %>


              </div>
            <% end %>
          </div>
          <%= form_with model: [@post, @post_comment] do |f| %>
            <div class="form-group">
              <%= f.text_area :comment, rows: '5', placeholder: "コメント" %>
            </div>
            <%= f.submit "送信", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>